### ISSUE TITLE
Viewing a pattern in the "full" preview size and then clicking "Fullscreen" --> breaks the UI and a user cannot go back to regular view or change the preview size

### ISSUE THREAD

**Issue by rockymountainhigh1943** [basaltinc/bedrock#174]
![full-screen-full](https://user-images.githubusercontent.com/247837/51002911-adf59880-14e9-11e9-9918-b340b8ee23bc.gif)

**Comment by joekarasek** [comment]
Looks like this was resolved with the refactors of the pattern view page. Marking as done.
