### ISSUE TITLE
Design tokens > demos should be organized by size

### ISSUE THREAD

**Issue by rockymountainhigh1943** [basaltinc/bedrock#80]
Update: Lets get some ordering in demos where ever possible.
- [ ] Font Size (numerical)
- [ ] Spacing + Sizing (numerical)
- [ ] Font Family (alphabetic)
- [ ] Colors (alphabetic by name)
- [ ] Line height (numerical)
- [ ] Border Radius (numerical)
Note: some items on the list above will have a couple demoing components, for example colors is actually text-color, background-color, hr-color, etc

Right now the order of font size demos is confusing. It doesn't appear to be ordered by name, type, or by value. We should order this list by EITHER **type** (h tags, t-shirt sizes, etc) OR **value**.

**Comment by joekarasek** [comment]
Closing this for two reasons:
1) This issue has been addressed with the use of json format for source data of tokens to knapsack, allowing for ordering of the data as it comes into the system. The order in the source files is preserved, so it is easy to edit this from code.
2) While the concept of sortable fields is nice, there are a lot of edge cases, such as the need to strip and convert units, relative units (like em's), etc. that would make sorting the values tricky.
